# List of languages comes from Q1, might not be exhaustive
LANGUAGES = {
    "en": "English",
    "nl": "Dutch",
    "de": "German",
    "fr": "French",
    "ab": "Abkhazian",
    "af": "Afrikaans",
    "ak": "Akan",
    "am": "Amharic",
    "an": "Aragonese",
    "ar": "Arabic",
    "arc": "Aramaic",
    "ary": "Moroccan Arabic",
    "arz": "Egyptian Arabic",
    "as": "Assamese",
    "ast": "Asturian",
    "az": "Azerbaijani",
    "azb": "South Azerbaijani",
    "ba": "Bashkir",
    "bar": "Bavarian",
    "bcl": "Central Bikol",
    "be": "Belarusian",
    "be-tarask": "Belarusian (Taraškievica orthography)",
    "bg": "Bulgarian",
    "bho": "Bhojpuri",
    "bn": "Bangla",
    "bo": "Tibetan",
    "br": "Breton",
    "bs": "Bosnian",
    "bxr": "Russia Buriat",
    "ca": "Catalan",
    "cdo": "Min Dong Chinese",
    "ce": "Chechen",
    "ceb": "Cebuano",
    "chr": "Cherokee",
    "ckb": "Central Kurdish",
    "co": "Corsican",
    "crh": "Crimean Tatar",
    "cs": "Czech",
    "csb": "Kashubian",
    "cv": "Chuvash",
    "cy": "Welsh",
    "da": "Danish",
    "dag": "Dagbani",
    "de-at": "Austrian German",
    "de-ch": "Swiss High German",
    "diq": "Zazaki",
    "dsb": "Lower Sorbian",
    "el": "Greek",
    "en-ca": "Canadian English",
    "en-gb": "British English",
    "en-us": "American English",
    "eo": "Esperanto",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "ext": "Extremaduran",
    "fa": "Persian",
    "fi": "Finnish",
    "fj": "Fijian",
    "fo": "Faroese",
    "frr": "Northern Frisian",
    "fy": "Western Frisian",
    "ga": "Irish",
    "gcr": "Guianan Creole",
    "gd": "Scottish Gaelic",
    "gl": "Galician",
    "gn": "Guarani",
    "gsw": "Swiss German",
    "gu": "Gujarati",
    "hak": "Hakka Chinese",
    "he": "Hebrew",
    "hi": "Hindi",
    "hif": "Fiji Hindi",
    "hr": "Croatian",
    "ht": "Haitian Creole",
    "hu": "Hungarian",
    "hy": "Armenian",
    "hyw": "Western Armenian",
    "ia": "Interlingua",
    "id": "Indonesian",
    "ie": "Interlingue",
    "ilo": "Iloko",
    "inh": "Ingush",
    "io": "Ido",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "jam": "Jamaican Creole English",
    "jbo": "Lojban",
    "jv": "Javanese",
    "ka": "Georgian",
    "kab": "Kabyle",
    "kk": "Kazakh",
    "kn": "Kannada",
    "ko": "Korean",
    "krc": "Karachay-Balkar",
    "ks": "Kashmiri",
    "ku": "Kurdish",
    "kw": "Cornish",
    "ky": "Kyrgyz",
    "la": "Latin",
    "lb": "Luxembourgish",
    "lez": "Lezghian",
    "lfn": "Lingua Franca Nova",
    "li": "Limburgish",
    "lij": "Ligurian",
    "lld": "Ladin",
    "lmo": "Lombard",
    "lo": "Lao",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "lzh": "Literary Chinese",
    "lzz": "Laz",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mr": "Marathi",
    "ms": "Malay",
    "ms-arab": "Malay (Jawi script)",
    "mt": "Maltese",
    "mwl": "Mirandese",
    "my": "Burmese",
    "nah": "Nāhuatl",
    "nan": "Min Nan Chinese",
    "nap": "Neapolitan",
    "nb": "Norwegian Bokmål",
    "nds": "Low German",
    "nds-nl": "Low Saxon",
    "ne": "Nepali",
    "nn": "Norwegian Nynorsk",
    "nov": "Novial",
    "nqo": "N’Ko",
    "nrm": "Norman",
    "nv": "Navajo",
    "ny": "Nyanja",
    "oc": "Occitan",
    "om": "Oromo",
    "or": "Odia",
    "pa": "Punjabi",
    "pam": "Pampanga",
    "pap": "Papiamento",
    "pfl": "Palatine German",
    "pl": "Polish",
    "pms": "Piedmontese",
    "pnb": "Western Punjabi",
    "ps": "Pashto",
    "pt": "Portuguese",
    "pt-br": "Brazilian Portuguese",
    "qu": "Quechua",
    "rki": "Arakanese",
    "rmy": "Vlax Romani",
    "ro": "Romanian",
    "ru": "Russian",
    "rue": "Rusyn",
    "sat": "Santali",
    "scn": "Sicilian",
    "sco": "Scots",
    "sd": "Sindhi",
    "se": "Northern Sami",
    "sgs": "Samogitian",
    "sh": "Serbo-Croatian",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "smn": "Inari Sami",
    "sms": "Skolt Sami",
    "sn": "Shona",
    "so": "Somali",
    "sq": "Albanian",
    "sr": "Serbian",
    "sr-ec": "Serbian (Cyrillic script)",
    "sr-el": "Serbian (Latin script)",
    "stq": "Saterland Frisian",
    "su": "Sundanese",
    "sv": "Swedish",
    "sw": "Swahili",
    "szl": "Silesian",
    "ta": "Tamil",
    "te": "Telugu",
    "tg": "Tajik",
    "th": "Thai",
    "tl": "Tagalog",
    "tok": "Toki Pona",
    "tr": "Turkish",
    "ts": "Tsonga",
    "tt": "Tatar",
    "tt-cyrl": "Tatar (Cyrillic script)",
    "tt-latn": "Tatar (Latin script)",
    "tw": "Twi",
    "udm": "Udmurt",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "vec": "Venetian",
    "vep": "Veps",
    "vi": "Vietnamese",
    "vo": "Volapük",
    "wa": "Walloon",
    "war": "Waray",
    "wuu": "Wu Chinese",
    "xh": "Xhosa",
    "xmf": "Mingrelian",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yue": "Cantonese",
    "za": "Zhuang",
    "zh": "Chinese",
    "zh-cn": "Chinese (China)",
    "zh-hans": "Simplified Chinese",
    "zh-hant": "Traditional Chinese",
    "zh-hk": "Chinese (Hong Kong)",
    "zh-mo": "Chinese (Macau)",
    "zh-my": "Chinese (Malaysia)",
    "zh-sg": "Chinese (Singapore)",
    "zh-tw": "Chinese (Taiwan)",
    "zu": "Zulu"
}